webtalk_init -webtalk_dir /home/nolan/Documents/Vivado/project_1/project_1.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 2 11:37:49 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210802122_0_0_775" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "nfmul9ganenel6k3e4qfk0d9um" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Fedora" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Fedora release 21 (Twenty One)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3370.312 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1427996514000" -context "sdk\\\\hardware/1427996514000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1427996514000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1427996514000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1427996514000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1427996514000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1427996514000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1427996514000"
webtalk_add_data -client sdk -key uid -value "1427996656000" -context "sdk\\\\bsp/1427996656000"
webtalk_add_data -client sdk -key hwid -value "1427996514000" -context "sdk\\\\bsp/1427996656000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1427996656000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1427996656000"
webtalk_transmit -clientid 1103290571 -regid "210802122_0_0_775" -xml /home/nolan/Documents/Vivado/project_1/project_1.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/nolan/Documents/Vivado/project_1/project_1.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/nolan/Documents/Vivado/project_1/project_1.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
