webtalk_init -webtalk_dir /home/nolan/Documents/new_vivado/radspwi/project_1/project_1.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 4 23:55:11 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210802122_1777507930_0_469" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "tfh139bvsr5ep8q96d68b3j3ne" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.1_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Fedora" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Fedora release 21 (Twenty One)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3105.664 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1433476612000" -context "sdk\\\\bsp/1433476612000"
webtalk_add_data -client sdk -key hwid -value "1433464652000" -context "sdk\\\\bsp/1433476612000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1433476612000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1433476612000"
webtalk_transmit -clientid 969915198 -regid "210802122_1777507930_0_469" -xml /home/nolan/Documents/new_vivado/radspwi/project_1/project_1.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/nolan/Documents/new_vivado/radspwi/project_1/project_1.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/nolan/Documents/new_vivado/radspwi/project_1/project_1.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
